version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_PROJECT_ID: "cubee-259905"
      GOOGLE_COMPUTE_ZONE: "asia-east1-a"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Environment Variable
          command: |
            TAG=release-$(echo $CIRCLE_SHA1 | cut -c 1-8)-$CIRCLE_BUILD_NUM
            mkdir -p ./my-persist-workspace
            touch ./my-persist-workspace/persist-env-var.txt
            echo "export IMAGE_TAG=$TAG" > ./my-persist-workspace/persist-env-var.txt
            cat ./my-persist-workspace/persist-env-var.txt >> $BASH_ENV
      - run:
          name: Build Docker Image
          command: |
            IMAGE_TAG=release-$(echo $CIRCLE_SHA1 | cut -c 1-8)-$CIRCLE_BUILD_NUM
            docker build \
              -t gocreating/money-generator:${IMAGE_TAG} \
              -f ./Dockerfile .
            docker tag gocreating/money-generator:${IMAGE_TAG} gocreating/money-generator:latest
      - run:
          name: Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push gocreating/money-generator:latest
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ./gcloud-service-key.json
            gcloud auth activate-service-account --key-file=./gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            rm ./gcloud-service-key.json
      - run:
          name: Deploy to Production
          command: |
            gcloud compute instances reset money-generator-prod
      - persist_to_workspace:
          root: ./my-persist-workspace
          paths:
            - persist-env-var.txt
